### ISSUE TITLE
uncaught error in `.set()`

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#128]
```
await p2p.set({
  url: 'd88601936b3669913df4f5673204622fb87d8fbdba732ea63ff5cde195e76346',
  title: 't',
  description: '',
  subtype: 'Q17737',
  parents: [
    'dat://713a22aba64c4d0f07a48badeb03e0db21a119da64cacb5f50e325584011ba84'
  ]
}

✖ TypeError: arr is not iterable
    at validateNoFutureParents (/Users/julian/dev/hypergraph-xyz/cli/node_modules/@p2pcommons/sdk-js/index.js:646:25)
    at SDK.validateParams (/Users/julian/dev/hypergraph-xyz/cli/node_modules/@p2pcommons/sdk-js/index.js:682:9)
    at SDK.set (/Users/julian/dev/hypergraph-xyz/cli/node_modules/@p2pcommons/sdk-js/index.js:759:18)
    at async Object.exports.handler (/Users/julian/dev/hypergraph-xyz/cli/actions/update.js:154:3)
    at async hypergraph (/Users/julian/dev/hypergraph-xyz/cli/index.js:42:3)
```

I'm going to debug this now

**Comment by juliangruber** [comment]
It looks like

https://github.com/p2pcommons/sdk-js/blob/bf6a3f5950c99003827ce598bce84565442684cd/index.js#L682

should be

```js
        validateNoFutureParents(original.parents, p)
```

and that this code is untested. This patch seems to work for me :)
