### ISSUE TITLE
subleveldown error

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#13]
This is happening for me when I initialize the sdk now:

```
 λ  cli (master) : ./bin/hypergraph.js
✔ Pick an action › Create a module
✔ Select type › Content
/Users/julian/dev/hypergraph-xyz/cli/node_modules/subleveldown/leveldown.js:86
  this.db.open(function (err) {
          ^

TypeError: Cannot read property 'open' of undefined
    at SubDown._open (/Users/julian/dev/hypergraph-xyz/cli/node_modules/subleveldown/leveldown.js:86:11)
    at SubDown.AbstractLevelDOWN.open (/Users/julian/dev/hypergraph-xyz/cli/node_modules/subleveldown/node_modules/abstract-leveldown/abstract-leveldown.js:33:8)
    at DB._open (/Users/julian/dev/hypergraph-xyz/cli/node_modules/encoding-down/index.js:57:11)
    at DB.AbstractLevelDOWN.open (/Users/julian/dev/hypergraph-xyz/cli/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-leveldown.js:33:8)
    at DeferredLevelDOWN._open (/Users/julian/dev/hypergraph-xyz/cli/node_modules/deferred-leveldown/deferred-leveldown.js:30:12)
    at DeferredLevelDOWN.AbstractLevelDOWN.open (/Users/julian/dev/hypergraph-xyz/cli/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:33:8)
    at LevelUP.open (/Users/julian/dev/hypergraph-xyz/cli/node_modules/levelup/lib/levelup.js:117:11)
    at new LevelUP (/Users/julian/dev/hypergraph-xyz/cli/node_modules/levelup/lib/levelup.js:59:8)
    at LevelUP (/Users/julian/dev/hypergraph-xyz/cli/node_modules/levelup/lib/levelup.js:30:12)
    at module.exports (/Users/julian/dev/hypergraph-xyz/cli/node_modules/subleveldown/index.js:9:10)
```

**Comment by juliangruber** [comment]
I could resolve this by deleting my `~/.p2pcommons`

**Comment by dpaez** [comment]
Oh interesting. I'll see if I can reproduce it.

**Comment by juliangruber** [comment]
Just got this again in CI:

```
    /home/runner/work/cli/cli/node_modules/subleveldown/leveldown.js:86
      this.db.open(function (err) {
              ^
    TypeError: Cannot read property 'open' of undefined
        at SubDown._open (/home/runner/work/cli/cli/node_modules/subleveldown/leveldown.js:86:11)
        at SubDown.AbstractLevelDOWN.open (/home/runner/work/cli/cli/node_modules/subleveldown/node_modules/abstract-leveldown/abstract-leveldown.js:33:8)
        at DB._open (/home/runner/work/cli/cli/node_modules/encoding-down/index.js:57:11)
        at DB.AbstractLevelDOWN.open (/home/runner/work/cli/cli/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-leveldown.js:33:8)
        at DeferredLevelDOWN._open (/home/runner/work/cli/cli/node_modules/deferred-leveldown/deferred-leveldown.js:30:12)
        at DeferredLevelDOWN.AbstractLevelDOWN.open (/home/runner/work/cli/cli/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:33:8)
        at LevelUP.open (/home/runner/work/cli/cli/node_modules/levelup/lib/levelup.js:117:11)
        at new LevelUP (/home/runner/work/cli/cli/node_modules/levelup/lib/levelup.js:59:8)
        at LevelUP (/home/runner/work/cli/cli/node_modules/levelup/lib/levelup.js:30:12)
        at module.exports (/home/runner/work/cli/cli/node_modules/subleveldown/index.js:9:10)
```

**Comment by juliangruber** [comment]
I figured it out! It's actually a different error:

```
Error [OpenError]: IO error: lock
/var/folders/rs/j3w8q_p57v543cp27jdcnn6r0000gn/T/1573127027809-0.00848761397909703/db/LOCK:
Resource temporarily unavailable
  at /Users/julian/dev/hypergraph-xyz/cli/node_modules/levelup/lib/levelup.js:119:23
  at /Users/julian/dev/hypergraph-xyz/cli/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
  at /Users/julian/dev/hypergraph-xyz/cli/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
  at /Users/julian/dev/hypergraph-xyz/cli/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
  at /Users/julian/dev/hypergraph-xyz/cli/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:36:14
```

The original error doesn't show however because of a missing `return` here:

https://github.com/p2pcommons/sdk-js/blob/f9a3417806913c07a9203dc8b49ce80321ab17a5/index.js#L138

**Comment by dpaez** [comment]
oh wow, great finding @juliangruber I'll add the missing `return`.
