### ISSUE TITLE
Clone method unreliable

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/sdk-js#285]
## Description

The clone method proves unreliable in cloning modules, both unversioned and versioned.

## To Reproduce

```js
const SDK = require('@p2pcommons/sdk-js')

const baseDir = '.test-sdk'
const x = new SDK({ baseDir })

const chris = "2ae99d1441b7605a9775b2e1c7835d4ddaaafc9472b0a0fd6e9bf9607dd210b5"
const hans = "e9ccc00b466a4d437f387e352f7098af5b022b8774a96852839a32ba19f47cc8"
const martin = "35c06f644725a71c24a2f83ed08489ee373b3f49dfdab44bbbca25549a67bdee"
const unversionedKey4 = "43eb22e34ad1f03615200dfcf16e092b8f571cc88b1355d0e9b77845b4052832"
const version4 = 25

;(async () => { 
    await x.ready()
    console.log('Started client')
    await x.clone(chris)
    console.log(`Successfully cloned ${chris}`)

    await x.clone(hans)
    console.log(`Successfully cloned ${hans}`)

    await x.clone(martin)
    console.log(`Successfully cloned ${martin}`)

    await x.clone(unversionedKey4, version4)
    console.log(`Successfully cloned ${unversionedKey4}+${version4}`)
})()

```

## Expected behavior

All modules available cloned successfully in one run.

## Actual behavior

Some modules get cloned on first run (`chris`), others on second (`hans`), others not at all (`martin` and checkout).

## System

- OS (incl. version): macOS 11.2.2
- SDK version:`main@ea8b6c12cefdfe5619d78be81d1756e130e4df4b`

## Additional context

All modules available from Hypegraph vault and permanent seeders

<details>
    <summary>First run output</summary>

```bash
chjh@module test-sdk-checkout % node index.js 
Started client
Successfully cloned 2ae99d1441b7605a9775b2e1c7835d4ddaaafc9472b0a0fd6e9bf9607dd210b5
(node:30500) UnhandledPromiseRejectionWarning: Error: clone: Problems fetching external module
    at SDK.getFromSwarm (/Users/chjh/playground/test-sdk-checkout/node_modules/@p2pcommons/sdk-js/index.js:1760:13)
(node:30500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>
<details>
    <summary>Second run output</summary>

```bash
chjh@module test-sdk-checkout % node index.js
Started client
Successfully cloned 2ae99d1441b7605a9775b2e1c7835d4ddaaafc9472b0a0fd6e9bf9607dd210b5
Successfully cloned e9ccc00b466a4d437f387e352f7098af5b022b8774a96852839a32ba19f47cc8
(node:30562) UnhandledPromiseRejectionWarning: Error: clone: Problems fetching external module
    at SDK.getFromSwarm (/Users/chjh/playground/test-sdk-checkout/node_modules/@p2pcommons/sdk-js/index.js:1760:13)
(node:30562) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:30562) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

**Comment by chartgerink** [comment]
Following up on this: the `martin` module was really unavailable (not hosted on permanent-seeder instances). This was not an issue of the sdk after all. The `UnhandledPromiseRejectionWarning` occurs sporadically in testing for me.

The checkout remains an issue. From testing a bit more, it seems like the `drive.checkout()` creates a valid Hyperdrive instance, but that it doesn't connect/download all the info and gets stuck there for some reason. When I remove the checkout, the drive gets downloaded instantaneously. The checked out version is available on the network (I can access it from Beaker).

@dpaez and I will be working on this during the next week :)
