### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by juliangruber** [p2pcommons/sdk-js#5]
I'm getting this error with `0.2.0`:

```
Unhandled rejection Error: Command failed: /usr/local/bin/git checkout sub-signalhub
error: pathspec 'sub-signalhub' did not match any file(s) known to git.

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

**Comment by juliangruber** [comment]
See also https://github.com/RangerMauve/discovery-swarm-web/issues/7#issuecomment-543092394

**Comment by juliangruber** [comment]
`0.1.0` also is unable to install due to this
