### ISSUE TITLE
Stack trace when trying to set profile parents

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#98]
When trying to set parents for a profile (which is not allowed), I get a stack trace instead of a validation error:

```
PS D:\Websites\hypergraph-xyz\cli> hypergraph update 1097aa856929ead875375bc3c1a6a5f101f51336cd2536e42977a0531e5e7095 -p 3d214b39d3c48035aac246a4dc7e3c63212a10d72b2af957a9d67cf4dc29d36e
× Error: p2pcommonsextra fields (parents)
    at errorHook (D:\Websites\hypergraph-xyz\cli\node_modules\@p2pcommons\sdk-js\index.js:44:15)
    at hook (D:\Websites\hypergraph-xyz\cli\node_modules\@avro\types\lib\types.js:587:17)
    at RecordType.checkRecord$ [as _check] (eval at RecordType._createChecker (D:\Websites\hypergraph-xyz\cli\node_modules\@avro\types\lib\types.js:2029:10), <anonymous>:9:14)
    at RecordType.checkProfile [as _check] (eval at RecordType._createChecker (D:\Websites\hypergraph-xyz\cli\node_modules\@avro\types\lib\types.js:2029:10), <anonymous>:25:13)
    at RecordType.Type.isValid (D:\Websites\hypergraph-xyz\cli\node_modules\@avro\types\lib\types.js:590:15)
    at assertValid (D:\Websites\hypergraph-xyz\cli\node_modules\@p2pcommons\sdk-js\index.js:35:15)
    at SDK.set (D:\Websites\hypergraph-xyz\cli\node_modules\@p2pcommons\sdk-js\index.js:668:5)
    at async Object.exports.handler (D:\Websites\hypergraph-xyz\cli\actions\update.js:151:3)
    at async hypergraph (D:\Websites\hypergraph-xyz\cli\index.js:43:3)
```

**Comment by juliangruber** [comment]
@dpaez As far as I understand it the stack trace is printed because the error isn't a `ValidationError`

**Comment by dpaez** [comment]
It is thrown by a validation function, but it's a generic error at the moment. We can make it a validation error. 

The error tries to say that there are extra parameters not expected for such model/schema.

**Comment by dpaez** [comment]
hi folks, I've changed this and now throws a validation error. Is that ok? or do you consider another type of error would suit better? ✌️

**Comment by juliangruber** [comment]
ValidationError sounds like a great fit :)
